//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _56jtyj.ModelDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string Name { get; set; }
        public string LastName { get; set; }
        public Nullable<int> Age { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    }
}
